MODELS = [
    # ===== 预测模型 =====
    {
        "category": "预测",
        "name": "线性回归",
        "tags": ["回归", "监督学习", "入门"],
        "summary": "建立自变量与因变量之间的线性关系，最基础的预测模型。",
        "when": "数据量适中，变量间呈线性关系，需要可解释性强的模型。",
        "python_libs": "sklearn.linear_model.LinearRegression, statsmodels.api.OLS",
        "mcm_type": ["A", "B", "C", "D", "E", "F"],
        "difficulty": "入门",
    },
    {
        "category": "预测",
        "name": "ARIMA 时间序列",
        "tags": ["时间序列", "统计", "平稳性"],
        "summary": "差分自回归移动平均模型，处理平稳时间序列的经典方法。",
        "when": "有明显时间趋势的单变量预测问题，如销量、温度、股价。",
        "python_libs": "statsmodels.tsa.arima.model.ARIMA, pmdarima.auto_arima",
        "mcm_type": ["C", "E"],
        "difficulty": "中等",
    },
    {
        "category": "预测",
        "name": "灰色预测 GM(1,1)",
        "tags": ["小样本", "不确定系统", "灰色系统"],
        "summary": "适用于数据量少、信息不完全场景的预测模型，国赛高频。",
        "when": "数据点少于 10 个，无法使用统计或机器学习方法。",
        "python_libs": "numpy (自行实现), greytheory 库",
        "mcm_type": ["A", "E"],
        "difficulty": "简单",
    },
    {
        "category": "预测",
        "name": "BP 神经网络",
        "tags": ["深度学习", "非线性拟合", "万能逼近"],
        "summary": "反向传播神经网络，可逼近任意非线性函数。",
        "when": "数据量大、非线性关系强，精度要求高。",
        "python_libs": "sklearn.neural_network.MLPRegressor, tensorflow.keras",
        "mcm_type": ["A", "C", "D", "E"],
        "difficulty": "中等",
    },
    {
        "category": "预测",
        "name": "XGBoost",
        "tags": ["集成学习", "梯度提升", "Kaggle 利器"],
        "summary": "梯度提升树算法，精度极高，竞赛和工业界首选。",
        "when": "结构化数据（表格数据），特征维度适中，追求预测精度。",
        "python_libs": "xgboost.XGBRegressor, xgboost.XGBClassifier",
        "mcm_type": ["C"],
        "difficulty": "中等",
    },
    {
        "category": "预测",
        "name": "Prophet",
        "tags": ["时间序列", "季节性", "假期效应"],
        "summary": "Facebook 开源的时间序列预测工具，自动处理季节性和趋势。",
        "when": "有明显的日/周/年周期性，需要处理假期效应。",
        "python_libs": "prophet.Prophet",
        "mcm_type": ["C", "E"],
        "difficulty": "简单",
    },
    {
        "category": "预测",
        "name": "SIR 传染病模型",
        "tags": ["微分方程", "动力学", "传播"],
        "summary": "易感-感染-康复仓室模型，用于模拟传播动力学。",
        "when": "疾病传播、信息扩散、谣言传播等问题。",
        "python_libs": "scipy.integrate.solve_ivp",
        "mcm_type": ["A"],
        "difficulty": "中等",
    },

    # ===== 优化模型 =====
    {
        "category": "优化",
        "name": "线性规划",
        "tags": ["运筹学", "约束优化", "单纯形法"],
        "summary": "在线性约束下求线性目标函数的最优解。",
        "when": "目标函数和约束条件均为线性，如资源分配、运输调度。",
        "python_libs": "scipy.optimize.linprog, pulp.LpProblem",
        "mcm_type": ["A", "B", "D", "E"],
        "difficulty": "入门",
    },
    {
        "category": "优化",
        "name": "整数规划",
        "tags": ["离散优化", "0-1规划", "组合优化"],
        "summary": "变量必须为整数的线性规划，包含 0-1 规划等特例。",
        "when": "决策变量为离散值（如选址、指派、背包问题）。",
        "python_libs": "pulp, ortools.sat, scipy.optimize.milp",
        "mcm_type": ["B", "D"],
        "difficulty": "中等",
    },
    {
        "category": "优化",
        "name": "动态规划",
        "tags": ["最优子结构", "多阶段决策", "记忆化"],
        "summary": "将复杂问题分解为子问题逐步求解，避免重复计算。",
        "when": "多阶段决策问题，如最短路径、资源分配、生产计划。",
        "python_libs": "标准库实现, functools.lru_cache",
        "mcm_type": ["B"],
        "difficulty": "中等",
    },
    {
        "category": "优化",
        "name": "遗传算法 (GA)",
        "tags": ["进化算法", "全局优化", "启发式"],
        "summary": "模拟自然选择和遗传机制的随机搜索算法。",
        "when": "目标函数不可微、多峰、NP-hard 问题，传统方法难以求解。",
        "python_libs": "deap, pymoo, geneticalgorithm",
        "mcm_type": ["B", "D", "E", "F"],
        "difficulty": "中等",
    },
    {
        "category": "优化",
        "name": "粒子群算法 (PSO)",
        "tags": ["群智能", "连续优化", "收敛快"],
        "summary": "模拟鸟群觅食行为的群体智能优化算法。",
        "when": "连续变量的全局优化，收敛速度快于遗传算法。",
        "python_libs": "pyswarms, pymoo.algorithms.soo.PSO",
        "mcm_type": ["A", "B", "D"],
        "difficulty": "简单",
    },
    {
        "category": "优化",
        "name": "模拟退火 (SA)",
        "tags": ["概率突跳", "全局搜索", "Metropolis"],
        "summary": "模拟物理退火过程，以概率接受较差解以跳出局部最优。",
        "when": "组合优化问题（TSP、排课、布局），需要逃离局部最优。",
        "python_libs": "scipy.optimize.dual_annealing, simanneal",
        "mcm_type": ["B", "D"],
        "difficulty": "中等",
    },
    {
        "category": "优化",
        "name": "多目标优化 (NSGA-II)",
        "tags": ["Pareto最优", "非支配排序", "多准则"],
        "summary": "同时优化多个冲突目标的进化算法，生成 Pareto 前沿。",
        "when": "存在多个互相冲突的优化目标，需要权衡方案。",
        "python_libs": "pymoo.algorithms.moo.nsga2.NSGA2",
        "mcm_type": ["D", "E", "F"],
        "difficulty": "进阶",
    },
    {
        "category": "优化",
        "name": "蚁群算法 (ACO)",
        "tags": ["路径优化", "信息素", "正反馈"],
        "summary": "模拟蚂蚁觅食时释放信息素寻路的算法。",
        "when": "路径规划、TSP 及其变体、网络路由。",
        "python_libs": "acopy, numpy (自行实现)",
        "mcm_type": ["B", "D"],
        "difficulty": "中等",
    },
    {
        "category": "优化",
        "name": "蒙特卡洛模拟",
        "tags": ["随机采样", "不确定性", "大数定律"],
        "summary": "通过大量随机采样近似求解确定性问题或模拟随机过程。",
        "when": "解析解不存在、不确定性量化、风险分析、敏感性检验。",
        "python_libs": "numpy.random, scipy.stats",
        "mcm_type": ["A", "B", "C", "D", "E", "F"],
        "difficulty": "简单",
    },

    # ===== 评价模型 =====
    {
        "category": "评价",
        "name": "层次分析法 (AHP)",
        "tags": ["多准则决策", "权重确定", "一致性检验"],
        "summary": "将复杂决策问题分解为目标-准则-方案层次结构，两两比较确定权重。",
        "when": "需要从多个方案中选择最优，或确定评价指标权重。",
        "python_libs": "pyahp, numpy (自行实现判断矩阵特征向量)",
        "mcm_type": ["D", "E", "F"],
        "difficulty": "入门",
    },
    {
        "category": "评价",
        "name": "TOPSIS 法",
        "tags": ["理想解", "距离评价", "客观排序"],
        "summary": "通过计算各方案与正负理想解的距离进行排序。",
        "when": "多指标多方案的综合评价，数据已标准化。",
        "python_libs": "numpy (自行实现), topsis-icm",
        "mcm_type": ["D", "E", "F"],
        "difficulty": "简单",
    },
    {
        "category": "评价",
        "name": "熵权法",
        "tags": ["客观赋权", "信息熵", "数据驱动"],
        "summary": "基于数据信息熵确定指标权重，完全客观，避免主观偏差。",
        "when": "需要客观确定各评价指标的重要性权重。",
        "python_libs": "numpy, scipy.stats.entropy",
        "mcm_type": ["D", "E", "F"],
        "difficulty": "简单",
    },
    {
        "category": "评价",
        "name": "模糊综合评价",
        "tags": ["模糊数学", "隶属度", "定性转定量"],
        "summary": "用模糊数学将定性评价转化为定量评价。",
        "when": "评价指标难以精确量化，存在模糊性和不确定性。",
        "python_libs": "numpy (自行实现), scikit-fuzzy",
        "mcm_type": ["E", "F"],
        "difficulty": "中等",
    },
    {
        "category": "评价",
        "name": "DEA 数据包络分析",
        "tags": ["效率评价", "投入产出", "非参数"],
        "summary": "评价多投入多产出决策单元相对效率的非参数方法。",
        "when": "评价多个同类单元的效率（企业、学校、医院）。",
        "python_libs": "pyDEA, pulp (建模求解)",
        "mcm_type": ["D", "F"],
        "difficulty": "中等",
    },

    # ===== 统计与数据处理 =====
    {
        "category": "统计",
        "name": "PCA 主成分分析",
        "tags": ["降维", "特征提取", "去相关"],
        "summary": "通过正交变换将高维相关变量转为低维不相关主成分。",
        "when": "数据维度过高、特征间存在多重共线性、需要降维可视化。",
        "python_libs": "sklearn.decomposition.PCA",
        "mcm_type": ["C", "D", "E"],
        "difficulty": "入门",
    },
    {
        "category": "统计",
        "name": "K-Means 聚类",
        "tags": ["无监督学习", "客户分群", "模式发现"],
        "summary": "将数据划分为 K 个簇，使簇内相似度高、簇间差异大。",
        "when": "需要对数据进行分组分类，但无标签数据。",
        "python_libs": "sklearn.cluster.KMeans",
        "mcm_type": ["C"],
        "difficulty": "入门",
    },
    {
        "category": "统计",
        "name": "假设检验",
        "tags": ["t检验", "方差分析", "显著性"],
        "summary": "用样本数据推断总体特征，判断差异是否具有统计显著性。",
        "when": "需要验证数据中的差异是真实的还是随机波动。",
        "python_libs": "scipy.stats.ttest_ind, scipy.stats.f_oneway",
        "mcm_type": ["A", "B", "C", "D", "E", "F"],
        "difficulty": "入门",
    },
    {
        "category": "统计",
        "name": "相关系数分析",
        "tags": ["Pearson", "Spearman", "相关性"],
        "summary": "量化变量间的线性或单调关系强度。",
        "when": "探索变量间关系，筛选特征，构造模型输入。",
        "python_libs": "pandas.DataFrame.corr, scipy.stats.pearsonr",
        "mcm_type": ["A", "B", "C", "D", "E", "F"],
        "difficulty": "入门",
    },
    {
        "category": "统计",
        "name": "Logistic 回归",
        "tags": ["二分类", "概率预测", "广义线性"],
        "summary": "用于二分类问题的概率预测模型，输出 0-1 之间的概率。",
        "when": "二分类预测问题（是/否、成功/失败），需要概率输出。",
        "python_libs": "sklearn.linear_model.LogisticRegression",
        "mcm_type": ["C", "F"],
        "difficulty": "入门",
    },

    # ===== 图论与网络 =====
    {
        "category": "图论",
        "name": "最短路径算法",
        "tags": ["Dijkstra", "Floyd", "网络优化"],
        "summary": "求图中两点间最短路径，或所有点对最短路径。",
        "when": "路径规划、物流配送、网络路由问题。",
        "python_libs": "networkx.shortest_path, scipy.sparse.csgraph",
        "mcm_type": ["B", "D"],
        "difficulty": "入门",
    },
    {
        "category": "图论",
        "name": "最小生成树 (MST)",
        "tags": ["Prim", "Kruskal", "连通性"],
        "summary": "连接所有节点的最小总权重生成树。",
        "when": "网络设计、管线铺设、聚类分析。",
        "python_libs": "networkx.minimum_spanning_tree",
        "mcm_type": ["B", "D"],
        "difficulty": "入门",
    },
    {
        "category": "图论",
        "name": "网络流 (最大流/最小割)",
        "tags": ["Ford-Fulkerson", "容量约束", "流量分配"],
        "summary": "在网络容量约束下求最大流量或最小割集。",
        "when": "交通流分配、通信网络带宽分配、供需匹配。",
        "python_libs": "networkx.maximum_flow, ortools.maxflow",
        "mcm_type": ["B", "D"],
        "difficulty": "中等",
    },
    {
        "category": "图论",
        "name": "PageRank",
        "tags": ["节点重要性", "随机游走", "链接分析"],
        "summary": "通过图的链接结构评估节点重要性的迭代算法。",
        "when": "评估网络节点的相对重要性（影响力、关键节点识别）。",
        "python_libs": "networkx.pagerank",
        "mcm_type": ["D"],
        "difficulty": "简单",
    },
    {
        "category": "图论",
        "name": "社区发现",
        "tags": ["Louvain", "模块度", "图聚类"],
        "summary": "探测网络中的社区结构，识别紧密连接的节点组。",
        "when": "社交网络、生物网络、交通网络的社区划分。",
        "python_libs": "networkx.algorithms.community, python-louvain",
        "mcm_type": ["D"],
        "difficulty": "中等",
    },

    # ===== 微分方程 =====
    {
        "category": "方程",
        "name": "常微分方程 (ODE)",
        "tags": ["动力学", "数值求解", "龙格-库塔"],
        "summary": "描述一个变量随另一个变量变化率的关系。",
        "when": "连续动态系统建模（物理过程、种群变化、化学反应）。",
        "python_libs": "scipy.integrate.solve_ivp, scipy.integrate.odeint",
        "mcm_type": ["A", "E"],
        "difficulty": "中等",
    },
    {
        "category": "方程",
        "name": "偏微分方程 (PDE)",
        "tags": ["有限差分", "有限元", "扩散方程"],
        "summary": "描述多变量函数及其偏导数关系的方程。",
        "when": "热传导、波动传播、流体力学、扩散过程。",
        "python_libs": "numpy (有限差分自行实现), fenics, scipy",
        "mcm_type": ["A"],
        "difficulty": "进阶",
    },
]
