MODELS = [
    # ===== 预测模型 =====
    {
        "category": "预测",
        "name": "线性回归",
        "tags": ["回归", "监督学习", "入门"],
        "summary": "建立自变量与因变量之间的线性关系，最基础的预测模型。",
        "when": "数据量适中，变量间呈线性关系，需要可解释性强的模型。",
        "python_libs": "sklearn.linear_model.LinearRegression, statsmodels.api.OLS",
        "mcm_type": ["A", "B", "C", "D", "E", "F"],
        "difficulty": "入门",
        "code_example": "from sklearn.linear_model import LinearRegression\nimport numpy as np\n\n# 模拟数据: y = 2*x1 + 3*x2 + 噪声\nX = np.random.randn(100, 2)\ny = 2 * X[:, 0] + 3 * X[:, 1] + np.random.randn(100) * 0.5\n\nmodel = LinearRegression().fit(X, y)\nprint(f\"系数: {model.coef_}, 截距: {model.intercept_:.2f}\")\nprint(f\"R²: {model.score(X, y):.3f}\")\n\n# 预测新数据\ny_pred = model.predict([[1.5, -0.5]])\nprint(f\"预测值: {y_pred[0]:.2f}\")",
    },
    {
        "category": "预测",
        "name": "ARIMA 时间序列",
        "tags": ["时间序列", "统计", "平稳性"],
        "summary": "差分自回归移动平均模型，处理平稳时间序列的经典方法。",
        "when": "有明显时间趋势的单变量预测问题，如销量、温度、股价。",
        "python_libs": "statsmodels.tsa.arima.model.ARIMA, pmdarima.auto_arima",
        "mcm_type": ["C", "E"],
        "difficulty": "中等",
        "code_example": "import numpy as np\nfrom statsmodels.tsa.arima.model import ARIMA\n\n# 模拟时间序列数据 (带趋势 + 噪声)\nt = np.arange(100)\ny = 0.5 * t + 2 * np.sin(t / 10) + np.random.randn(100) * 3\n\n# 拟合 ARIMA(2,1,2) 模型\nmodel = ARIMA(y, order=(2, 1, 2))\nfitted = model.fit()\nprint(fitted.summary())\n\n# 预测未来 10 步\nforecast = fitted.forecast(steps=10)\nprint(f\"未来10期预测: {forecast}\")",
    },
    {
        "category": "预测",
        "name": "灰色预测 GM(1,1)",
        "tags": ["小样本", "不确定系统", "灰色系统"],
        "summary": "适用于数据量少、信息不完全场景的预测模型，国赛高频。",
        "when": "数据点少于 10 个，无法使用统计或机器学习方法。",
        "python_libs": "numpy (自行实现), greytheory 库",
        "mcm_type": ["A", "E"],
        "difficulty": "简单",
        "code_example": "import numpy as np\n\ndef gm11(x0):\n    \"\"\"灰色预测 GM(1,1) 模型\"\"\"\n    x1 = np.cumsum(x0)  # 一次累加\n    z1 = (x1[:-1] + x1[1:]) / 2  # 紧邻均值\n    B = np.column_stack([-z1, np.ones_like(z1)])\n    Y = x0[1:]\n    a, b = np.linalg.lstsq(B, Y, rcond=None)[0]  # 最小二乘求参数\n    def predict(k):\n        return (x0[0] - b / a) * (1 - np.exp(a)) * np.exp(-a * k)\n    return predict\n\n# 示例: 只有 6 个数据点\nx0 = np.array([132, 155, 173, 195, 222, 248])\nf = gm11(x0)\nprint(f\"第7期预测: {f(6):.1f}\")",
    },
    {
        "category": "预测",
        "name": "BP 神经网络",
        "tags": ["深度学习", "非线性拟合", "万能逼近"],
        "summary": "反向传播神经网络，可逼近任意非线性函数。",
        "when": "数据量大、非线性关系强，精度要求高。",
        "python_libs": "sklearn.neural_network.MLPRegressor, tensorflow.keras",
        "mcm_type": ["A", "C", "D", "E"],
        "difficulty": "中等",
        "code_example": "from sklearn.neural_network import MLPRegressor\nfrom sklearn.preprocessing import StandardScaler\nimport numpy as np\n\nX = np.random.randn(500, 5)\ny = 3 * X[:, 0]**2 + np.sin(X[:, 1]) + np.random.randn(500) * 0.1\n\nscaler = StandardScaler()\nX_scaled = scaler.fit_transform(X)\n\nmodel = MLPRegressor(hidden_layer_sizes=(64, 32), max_iter=500, random_state=42)\nmodel.fit(X_scaled, y)\nprint(f\"训练 R²: {model.score(X_scaled, y):.3f}\")",
    },
    {
        "category": "预测",
        "name": "XGBoost",
        "tags": ["集成学习", "梯度提升", "Kaggle 利器"],
        "summary": "梯度提升树算法，精度极高，竞赛和工业界首选。",
        "when": "结构化数据（表格数据），特征维度适中，追求预测精度。",
        "python_libs": "xgboost.XGBRegressor, xgboost.XGBClassifier",
        "mcm_type": ["C"],
        "difficulty": "中等",
        "code_example": "from xgboost import XGBRegressor\nfrom sklearn.model_selection import train_test_split\nimport numpy as np\n\nX = np.random.randn(1000, 8)\ny = X[:, 0]**2 + X[:, 1] * X[:, 2] + np.random.randn(1000) * 0.5\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n\nmodel = XGBRegressor(n_estimators=100, max_depth=4, learning_rate=0.1, random_state=42)\nmodel.fit(X_train, y_train)\nprint(f\"测试 R²: {model.score(X_test, y_test):.3f}\")\nprint(f\"Top-3 特征重要性: {np.argsort(model.feature_importances_)[-3:][::-1]}\")",
    },
    {
        "category": "预测",
        "name": "Prophet",
        "tags": ["时间序列", "季节性", "假期效应"],
        "summary": "Facebook 开源的时间序列预测工具，自动处理季节性和趋势。",
        "when": "有明显的日/周/年周期性，需要处理假期效应。",
        "python_libs": "prophet.Prophet",
        "mcm_type": ["C", "E"],
        "difficulty": "简单",
        "code_example": "import pandas as pd\nfrom prophet import Prophet\n\n# 模拟两年日度数据\ndates = pd.date_range('2024-01-01', periods=730, freq='D')\ny = 100 + 0.2 * np.arange(730) + 20 * np.sin(2*np.pi*np.arange(730)/365.25) + np.random.randn(730)*5\ndf = pd.DataFrame({'ds': dates, 'y': y})\n\nmodel = Prophet(yearly_seasonality=True, weekly_seasonality=False)\nmodel.fit(df)\nfuture = model.make_future_dataframe(periods=90)\nforecast = model.predict(future)\nfig = model.plot(forecast)",
    },
    {
        "category": "预测",
        "name": "SIR 传染病模型",
        "tags": ["微分方程", "动力学", "传播"],
        "summary": "易感-感染-康复仓室模型，用于模拟传播动力学。",
        "when": "疾病传播、信息扩散、谣言传播等问题。",
        "python_libs": "scipy.integrate.solve_ivp",
        "mcm_type": ["A"],
        "difficulty": "中等",
        "code_example": "from scipy.integrate import solve_ivp\nimport numpy as np\n\ndef sir(t, y, beta, gamma):\n    S, I, R = y\n    N = S + I + R\n    dS = -beta * S * I / N\n    dI = beta * S * I / N - gamma * I\n    dR = gamma * I\n    return [dS, dI, dR]\n\n# 参数: beta=传播率, gamma=康复率\nsol = solve_ivp(sir, [0, 160], [999, 1, 0], args=(0.3, 0.1), max_step=1)\nprint(f\"峰值感染人数: {sol.y[1].max():.0f} (第{sol.y[1].argmax()}天)\")",
    },

    # ===== 优化模型 =====
    {
        "category": "优化",
        "name": "线性规划",
        "tags": ["运筹学", "约束优化", "单纯形法"],
        "summary": "在线性约束下求线性目标函数的最优解。",
        "when": "目标函数和约束条件均为线性，如资源分配、运输调度。",
        "python_libs": "scipy.optimize.linprog, pulp.LpProblem",
        "mcm_type": ["A", "B", "D", "E"],
        "difficulty": "入门",
        "code_example": "from scipy.optimize import linprog\n\n# min c^T x  s.t. A_ub x <= b_ub\nc = [-3, -2]  # 目标: max 3x1 + 2x2 → min -3x1-2x2\nA_ub = [[2, 1], [1, 2]]  # 约束矩阵\nb_ub = [4, 3]  # 约束右端\nbounds = [(0, None), (0, None)]  # x1, x2 >= 0\n\nres = linprog(c, A_ub=A_ub, b_ub=b_ub, bounds=bounds)\nprint(f\"最优解: x1={res.x[0]:.2f}, x2={res.x[1]:.2f}, 目标值={-res.fun:.2f}\")",
    },
    {
        "category": "优化",
        "name": "整数规划",
        "tags": ["离散优化", "0-1规划", "组合优化"],
        "summary": "变量必须为整数的线性规划，包含 0-1 规划等特例。",
        "when": "决策变量为离散值（如选址、指派、背包问题）。",
        "python_libs": "pulp, ortools.sat, scipy.optimize.milp",
        "mcm_type": ["B", "D"],
        "difficulty": "中等",
        "code_example": "from pulp import LpMaximize, LpProblem, LpVariable, lpSum\n\nprob = LpProblem(\"Knapsack\", LpMaximize)\nvalues = [10, 15, 7, 8, 12]\nweights = [2, 3, 1, 2, 4]\nx = [LpVariable(f\"x{i}\", cat=\"Binary\") for i in range(5)]\n\nprob += lpSum(values[i] * x[i] for i in range(5))\nprob += lpSum(weights[i] * x[i] for i in range(5)) <= 8\nprob.solve()\nprint(f\"最优值: {prob.objective.value():.0f}, 选中物品: {[i for i in range(5) if x[i].value() == 1]}\")",
    },
    {
        "category": "优化",
        "name": "动态规划",
        "tags": ["最优子结构", "多阶段决策", "记忆化"],
        "summary": "将复杂问题分解为子问题逐步求解，避免重复计算。",
        "when": "多阶段决策问题，如最短路径、资源分配、生产计划。",
        "python_libs": "标准库实现, functools.lru_cache",
        "mcm_type": ["B"],
        "difficulty": "中等",
        "code_example": "from functools import lru_cache\n\n@lru_cache(maxsize=None)\ndef knapsack(i, capacity):\n    \"\"\"0-1背包: 前i件物品, 容量capacity的最大价值\"\"\"\n    if i == 0 or capacity == 0:\n        return 0\n    w, v = weights[i-1], values[i-1]\n    if w > capacity:\n        return knapsack(i-1, capacity)\n    return max(knapsack(i-1, capacity), v + knapsack(i-1, capacity - w))\n\nvalues, weights = [10, 15, 7, 8, 12], [2, 3, 1, 2, 4]\nprint(f\"最大价值: {knapsack(5, 8)}\")",
    },
    {
        "category": "优化",
        "name": "遗传算法 (GA)",
        "tags": ["进化算法", "全局优化", "启发式"],
        "summary": "模拟自然选择和遗传机制的随机搜索算法。",
        "when": "目标函数不可微、多峰、NP-hard 问题，传统方法难以求解。",
        "python_libs": "deap, pymoo, geneticalgorithm",
        "mcm_type": ["B", "D", "E", "F"],
        "difficulty": "中等",
        "code_example": "import numpy as np\nfrom geneticalgorithm import geneticalgorithm as ga\n\n# 最小化 Rastrigin 函数 (多峰测试函数)\ndef f(X):\n    return 20 + X[0]**2 + X[1]**2 - 10*(np.cos(2*np.pi*X[0])+np.cos(2*np.pi*X[1]))\n\nalgorithm_param = {'max_num_iteration': 100, 'population_size': 50}\nmodel = ga(function=f, dimension=2, variable_boundaries=[[-5,5],[-5,5]],\n           algorithm_parameters=algorithm_param)\nmodel.run()\nprint(f\"最优解: {model.output_dict['variable']}\")",
    },
    {
        "category": "优化",
        "name": "粒子群算法 (PSO)",
        "tags": ["群智能", "连续优化", "收敛快"],
        "summary": "模拟鸟群觅食行为的群体智能优化算法。",
        "when": "连续变量的全局优化，收敛速度快于遗传算法。",
        "python_libs": "pyswarms, pymoo.algorithms.soo.PSO",
        "mcm_type": ["A", "B", "D"],
        "difficulty": "简单",
        "code_example": "import numpy as np\nfrom pyswarms.single import GlobalBestPSO\n\n# 最小化 sphere 函数\noptions = {'c1': 0.5, 'c2': 0.3, 'w': 0.9}\noptimizer = GlobalBestPSO(n_particles=50, dimensions=3, options=options)\n\ncost, pos = optimizer.optimize(lambda x: np.sum(x**2, axis=1), iters=200)\nprint(f\"最优位置: {np.round(pos, 4)}, 最优值: {cost:.6f}\")",
    },
    {
        "category": "优化",
        "name": "模拟退火 (SA)",
        "tags": ["概率突跳", "全局搜索", "Metropolis"],
        "summary": "模拟物理退火过程，以概率接受较差解以跳出局部最优。",
        "when": "组合优化问题（TSP、排课、布局），需要逃离局部最优。",
        "python_libs": "scipy.optimize.dual_annealing, simanneal",
        "mcm_type": ["B", "D"],
        "difficulty": "中等",
        "code_example": "from scipy.optimize import dual_annealing\nimport numpy as np\n\n# 寻找全局最小值 — Eggholder 函数 (经典困难问题)\ndef eggholder(x):\n    return -(x[0]+47)*np.sin(np.sqrt(abs(x[0]/2+(x[1]+47)))) - x[0]*np.sin(np.sqrt(abs(x[0]-(x[1]+47))))\n\nresult = dual_annealing(eggholder, bounds=[(-512, 512), (-512, 512)], maxiter=200)\nprint(f\"找到的最优值: {result.fun:.4f} at {np.round(result.x, 2)}\")",
    },
    {
        "category": "优化",
        "name": "多目标优化 (NSGA-II)",
        "tags": ["Pareto最优", "非支配排序", "多准则"],
        "summary": "同时优化多个冲突目标的进化算法，生成 Pareto 前沿。",
        "when": "存在多个互相冲突的优化目标，需要权衡方案。",
        "python_libs": "pymoo.algorithms.moo.nsga2.NSGA2",
        "mcm_type": ["D", "E", "F"],
        "difficulty": "进阶",
        "code_example": "import numpy as np\nfrom pymoo.algorithms.moo.nsga2 import NSGA2\nfrom pymoo.problems import get_problem\nfrom pymoo.optimize import minimize\n\n# ZDT1 — 经典双目标测试问题\nproblem = get_problem(\"zdt1\")\nalgorithm = NSGA2(pop_size=100)\nres = minimize(problem, algorithm, ('n_gen', 200), seed=42, verbose=False)\nprint(f\"Pareto前沿解数量: {len(res.F)}, 目标1范围: [{res.F[:,0].min():.3f},{res.F[:,0].max():.3f}]\")",
    },
    {
        "category": "优化",
        "name": "蚁群算法 (ACO)",
        "tags": ["路径优化", "信息素", "正反馈"],
        "summary": "模拟蚂蚁觅食时释放信息素寻路的算法。",
        "when": "路径规划、TSP 及其变体、网络路由。",
        "python_libs": "acopy, numpy (自行实现)",
        "mcm_type": ["B", "D"],
        "difficulty": "中等",
        "code_example": "import numpy as np\n\n# 简化的 ACO 求解 TSP\ndist = np.array([[0, 3, 4, 7], [3, 0, 2, 5], [4, 2, 0, 6], [7, 5, 6, 0]])\nn_cities = len(dist)\npheromone = np.ones((n_cities, n_cities)) * 0.1  # 初始化信息素\n\nfor _ in range(100):  # 100 轮迭代\n    path = [0]\n    unvisited = list(range(1, n_cities))\n    while unvisited:\n        probs = np.array([(pheromone[path[-1], j] / dist[path[-1], j]) for j in unvisited])\n        chosen = np.random.choice(unvisited, p=probs/probs.sum())\n        path.append(chosen); unvisited.remove(chosen)\n    length = sum(dist[path[i], path[(i+1)%n_cities]] for i in range(n_cities))\n    pheromone *= 0.9  # 挥发\n    for i in range(n_cities):\n        pheromone[path[i], path[(i+1)%n_cities]] += 1.0 / length\nprint(f\"最短路径长度: {length:.2f}\")",
    },
    {
        "category": "优化",
        "name": "蒙特卡洛模拟",
        "tags": ["随机采样", "不确定性", "大数定律"],
        "summary": "通过大量随机采样近似求解确定性问题或模拟随机过程。",
        "when": "解析解不存在、不确定性量化、风险分析、敏感性检验。",
        "python_libs": "numpy.random, scipy.stats",
        "mcm_type": ["A", "B", "C", "D", "E", "F"],
        "difficulty": "简单",
        "code_example": "import numpy as np\n\n# 蒙特卡洛估算 π\ndef estimate_pi(n_samples=100000):\n    x, y = np.random.rand(n_samples), np.random.rand(n_samples)\n    inside = (x**2 + y**2) <= 1\n    pi_est = 4 * inside.sum() / n_samples\n    return pi_est\n\n# 蒙特卡洛 VaR (风险价值)\nreturns = np.random.normal(0.001, 0.02, (10000, 252))\nannual_returns = (1 + returns).prod(axis=1) - 1\nvar_95 = np.percentile(annual_returns, 5)\nprint(f\"π ≈ {estimate_pi():.4f}, 95% VaR: {var_95:.2%}\")",
    },

    # ===== 评价模型 =====
    {
        "category": "评价",
        "name": "层次分析法 (AHP)",
        "tags": ["多准则决策", "权重确定", "一致性检验"],
        "summary": "将复杂决策问题分解为目标-准则-方案层次结构，两两比较确定权重。",
        "when": "需要从多个方案中选择最优，或确定评价指标权重。",
        "python_libs": "pyahp, numpy (自行实现判断矩阵特征向量)",
        "mcm_type": ["D", "E", "F"],
        "difficulty": "入门",
        "code_example": "import numpy as np\n\n# 判断矩阵 (1-9标度法, 3x3示例)\nA = np.array([[1,   3,   5],\n              [1/3, 1,   2],\n              [1/5, 1/2, 1]])\n\neigvals, eigvecs = np.linalg.eig(A)\nmax_eig = eigvals.real.max()\nweights = eigvecs[:, eigvals.real.argmax()].real\nweights /= weights.sum()\nCI = (max_eig - 3) / 2  # n=3\nCR = CI / 0.58  # RI=0.58 for n=3\nprint(f\"权重: {np.round(weights, 3)}, CR: {CR:.3f} {'✓ 通过' if CR < 0.1 else '✗ 不通过'}\")",
    },
    {
        "category": "评价",
        "name": "TOPSIS 法",
        "tags": ["理想解", "距离评价", "客观排序"],
        "summary": "通过计算各方案与正负理想解的距离进行排序。",
        "when": "多指标多方案的综合评价，数据已标准化。",
        "python_libs": "numpy (自行实现), topsis-icm",
        "mcm_type": ["D", "E", "F"],
        "difficulty": "简单",
        "code_example": "import numpy as np\n\n# 4方案 x 3指标 (已正向化)\nX = np.array([[8, 7, 2], [9, 6, 4], [6, 8, 3], [7, 9, 1]])\n\n# 归一化\nX_norm = X / np.sqrt((X**2).sum(axis=0))\n# 正/负理想解\nbest = X_norm.max(axis=0); worst = X_norm.min(axis=0)\n# 距离\nD_pos = np.sqrt(((X_norm - best)**2).sum(axis=1))\nD_neg = np.sqrt(((X_norm - worst)**2).sum(axis=1))\n# 相对贴近度\nscores = D_neg / (D_pos + D_neg)\nprint(f\"排名: {np.argsort(-scores) + 1}, 得分: {np.round(scores, 4)}\")",
    },
    {
        "category": "评价",
        "name": "熵权法",
        "tags": ["客观赋权", "信息熵", "数据驱动"],
        "summary": "基于数据信息熵确定指标权重，完全客观，避免主观偏差。",
        "when": "需要客观确定各评价指标的重要性权重。",
        "python_libs": "numpy, scipy.stats.entropy",
        "mcm_type": ["D", "E", "F"],
        "difficulty": "简单",
        "code_example": "import numpy as np\n\nX = np.array([[8, 7, 2], [9, 6, 4], [6, 8, 3], [7, 9, 1]])\n\n# 归一化 (效益型指标)\nP = X / X.sum(axis=0)\n# 计算熵值\nk = 1 / np.log(len(X))\ne = -k * (P * np.log(P.clip(1e-10))).sum(axis=0)\n# 熵权\nw = (1 - e) / (1 - e).sum()\nprint(f\"各指标权重: {np.round(w, 4)}\")",
    },
    {
        "category": "评价",
        "name": "模糊综合评价",
        "tags": ["模糊数学", "隶属度", "定性转定量"],
        "summary": "用模糊数学将定性评价转化为定量评价。",
        "when": "评价指标难以精确量化，存在模糊性和不确定性。",
        "python_libs": "numpy (自行实现), scikit-fuzzy",
        "mcm_type": ["E", "F"],
        "difficulty": "中等",
        "code_example": "import numpy as np\n\n# 评价等级: 差/中/良/优 的隶属度矩阵 (3指标 x 4等级)\nR = np.array([[0.1, 0.3, 0.4, 0.2],\n              [0.0, 0.2, 0.5, 0.3],\n              [0.2, 0.4, 0.3, 0.1]])\n# 指标权重\nW = np.array([0.35, 0.40, 0.25])\n# 模糊合成\nB = W @ R\n# 最大隶属度原则\nlevels = ['差', '中', '良', '优']\nprint(f\"综合评价向量: {np.round(B, 3)}\")\nprint(f\"评价结果: {levels[B.argmax()]}\")",
    },
    {
        "category": "评价",
        "name": "DEA 数据包络分析",
        "tags": ["效率评价", "投入产出", "非参数"],
        "summary": "评价多投入多产出决策单元相对效率的非参数方法。",
        "when": "评价多个同类单元的效率（企业、学校、医院）。",
        "python_libs": "pyDEA, pulp (建模求解)",
        "mcm_type": ["D", "F"],
        "difficulty": "中等",
        "code_example": "from pulp import LpProblem, LpVariable, lpSum, LpMinimize, value\n\n# CCR模型: 1投入2产出, 评价4个DMU\ninputs = [2, 3, 4, 2.5]\noutputs = [[3, 2], [4, 3], [5, 4], [3.5, 3]]\n\nfor k in range(4):\n    prob = LpProblem(f\"DEA_DMU{k}\", LpMinimize)\n    theta = LpVariable(\"theta\", 0, 1)\n    lam = [LpVariable(f\"l{j}\", 0) for j in range(4)]\n    prob += theta\n    prob += lpSum(inputs[j]*lam[j] for j in range(4)) <= theta*inputs[k]\n    for r in range(2):\n        prob += lpSum(outputs[j][r]*lam[j] for j in range(4)) >= outputs[k][r]\n    prob.solve()\n    print(f\"DMU{k} 效率: {value(prob.objective):.3f}\")",
    },

    # ===== 统计与数据处理 =====
    {
        "category": "统计",
        "name": "PCA 主成分分析",
        "tags": ["降维", "特征提取", "去相关"],
        "summary": "通过正交变换将高维相关变量转为低维不相关主成分。",
        "when": "数据维度过高、特征间存在多重共线性、需要降维可视化。",
        "python_libs": "sklearn.decomposition.PCA",
        "mcm_type": ["C", "D", "E"],
        "difficulty": "入门",
        "code_example": "from sklearn.decomposition import PCA\nimport numpy as np\n\nX = np.random.randn(200, 8)  # 200样本, 8特征\npca = PCA().fit(X)\n\n# 累计方差贡献率\ncumsum = np.cumsum(pca.explained_variance_ratio_)\nn_components = np.searchsorted(cumsum, 0.9) + 1  # 保留90%方差\nprint(f\"前{n_components}个主成分可解释{cumsum[n_components-1]:.1%}方差\")\n\nX_reduced = PCA(n_components=2).fit_transform(X)\nprint(f\"降维后形状: {X_reduced.shape}\")",
    },
    {
        "category": "统计",
        "name": "K-Means 聚类",
        "tags": ["无监督学习", "客户分群", "模式发现"],
        "summary": "将数据划分为 K 个簇，使簇内相似度高、簇间差异大。",
        "when": "需要对数据进行分组分类，但无标签数据。",
        "python_libs": "sklearn.cluster.KMeans",
        "mcm_type": ["C"],
        "difficulty": "入门",
        "code_example": "from sklearn.cluster import KMeans\nfrom sklearn.metrics import silhouette_score\nimport numpy as np\n\nX = np.vstack([\n    np.random.randn(100, 2) + [0, 0],\n    np.random.randn(100, 2) + [5, 5],\n    np.random.randn(100, 2) + [0, 5],\n])\n\nfor k in [2, 3, 4]:\n    labels = KMeans(n_clusters=k, n_init=10, random_state=42).fit_predict(X)\n    score = silhouette_score(X, labels)\n    print(f\"K={k}, 轮廓系数: {score:.4f}\")",
    },
    {
        "category": "统计",
        "name": "假设检验",
        "tags": ["t检验", "方差分析", "显著性"],
        "summary": "用样本数据推断总体特征，判断差异是否具有统计显著性。",
        "when": "需要验证数据中的差异是真实的还是随机波动。",
        "python_libs": "scipy.stats.ttest_ind, scipy.stats.f_oneway",
        "mcm_type": ["A", "B", "C", "D", "E", "F"],
        "difficulty": "入门",
        "code_example": "from scipy.stats import ttest_ind, f_oneway\nimport numpy as np\n\n# 两组独立样本 t检验\ngroup1 = np.random.normal(5.0, 1.5, 50)\ngroup2 = np.random.normal(5.8, 1.5, 50)\nt_stat, p_val = ttest_ind(group1, group2)\nprint(f\"t检验: t={t_stat:.3f}, p={p_val:.4f} {'***显著' if p_val < 0.05 else '不显著'}\")\n\n# 三组方差分析\nf_stat, p_f = f_oneway(group1, group2, np.random.normal(5.2, 1.5, 50))\nprint(f\"ANOVA: F={f_stat:.3f}, p={p_f:.4f} {'***显著' if p_f < 0.05 else '不显著'}\")",
    },
    {
        "category": "统计",
        "name": "相关系数分析",
        "tags": ["Pearson", "Spearman", "相关性"],
        "summary": "量化变量间的线性或单调关系强度。",
        "when": "探索变量间关系，筛选特征，构造模型输入。",
        "python_libs": "pandas.DataFrame.corr, scipy.stats.pearsonr",
        "mcm_type": ["A", "B", "C", "D", "E", "F"],
        "difficulty": "入门",
        "code_example": "import pandas as pd\nimport numpy as np\n\n# 构造相关数据\ndf = pd.DataFrame({\n    'x1': np.random.randn(100),\n    'x2': np.random.randn(100),\n    'y': np.random.randn(100),\n})\ndf['x2'] = df['x1'] * 0.7 + np.random.randn(100) * 0.3  # x2 与 x1 相关\ndf['y'] = df['x1'] * 0.5 + np.random.randn(100) * 0.8\n\ncorr = df.corr()\nprint(\"相关系数矩阵:\\n\", corr.round(3))\nprint(f\"\\n|x1-y| = {corr.loc['x1','y']:.3f}, |x1-x2| = {corr.loc['x1','x2']:.3f}\")",
    },
    {
        "category": "统计",
        "name": "Logistic 回归",
        "tags": ["二分类", "概率预测", "广义线性"],
        "summary": "用于二分类问题的概率预测模型，输出 0-1 之间的概率。",
        "when": "二分类预测问题（是/否、成功/失败），需要概率输出。",
        "python_libs": "sklearn.linear_model.LogisticRegression",
        "mcm_type": ["C", "F"],
        "difficulty": "入门",
        "code_example": "from sklearn.linear_model import LogisticRegression\nfrom sklearn.metrics import accuracy_score\nimport numpy as np\n\nX = np.random.randn(500, 4)\ny = (X[:, 0] + X[:, 1] * 0.5 > 0).astype(int)  # 线性决策边界\n\nmodel = LogisticRegression().fit(X, y)\nprobs = model.predict_proba(X)[:, 1]\npred = model.predict(X)\nprint(f\"准确率: {accuracy_score(y, pred):.3f}\")\nprint(f\"概率范围: [{probs.min():.2f}, {probs.max():.2f}]\")",
    },

    # ===== 图论与网络 =====
    {
        "category": "图论",
        "name": "最短路径算法",
        "tags": ["Dijkstra", "Floyd", "网络优化"],
        "summary": "求图中两点间最短路径，或所有点对最短路径。",
        "when": "路径规划、物流配送、网络路由问题。",
        "python_libs": "networkx.shortest_path, scipy.sparse.csgraph",
        "mcm_type": ["B", "D"],
        "difficulty": "入门",
        "code_example": "import networkx as nx\n\nG = nx.Graph()\nG.add_weighted_edges_from([\n    (0, 1, 4), (0, 2, 2), (1, 2, 1), (1, 3, 5),\n    (2, 3, 8), (2, 4, 10), (3, 4, 2), (3, 5, 6), (4, 5, 3)\n])\n\npath = nx.shortest_path(G, source=0, target=5, weight='weight')\nlength = nx.shortest_path_length(G, source=0, target=5, weight='weight')\nprint(f\"最短路径: {path}, 总距离: {length}\")",
    },
    {
        "category": "图论",
        "name": "最小生成树 (MST)",
        "tags": ["Prim", "Kruskal", "连通性"],
        "summary": "连接所有节点的最小总权重生成树。",
        "when": "网络设计、管线铺设、聚类分析。",
        "python_libs": "networkx.minimum_spanning_tree",
        "mcm_type": ["B", "D"],
        "difficulty": "入门",
        "code_example": "import networkx as nx\n\n# 6 个城市的距离图\nG = nx.Graph()\nG.add_weighted_edges_from([\n    (0,1,7), (0,3,5), (1,2,8), (1,3,9), (1,4,7),\n    (2,4,5), (3,4,15), (3,5,6), (4,5,8), (4,6,9), (5,6,11)\n])\n\nmst = nx.minimum_spanning_tree(G)\nedges = [(u, v, d['weight']) for u, v, d in mst.edges(data=True)]\ntotal = sum(d['weight'] for _, _, d in mst.edges(data=True))\nprint(f\"MST 边: {edges}\")\nprint(f\"总权重: {total}\")",
    },
    {
        "category": "图论",
        "name": "网络流 (最大流/最小割)",
        "tags": ["Ford-Fulkerson", "容量约束", "流量分配"],
        "summary": "在网络容量约束下求最大流量或最小割集。",
        "when": "交通流分配、通信网络带宽分配、供需匹配。",
        "python_libs": "networkx.maximum_flow, ortools.maxflow",
        "mcm_type": ["B", "D"],
        "difficulty": "中等",
        "code_example": "import networkx as nx\n\nG = nx.DiGraph()\nG.add_edge('S', 'A', capacity=10)\nG.add_edge('S', 'B', capacity=5)\nG.add_edge('A', 'B', capacity=3)\nG.add_edge('A', 'C', capacity=8)\nG.add_edge('B', 'C', capacity=7)\nG.add_edge('B', 'D', capacity=4)\nG.add_edge('C', 'T', capacity=10)\nG.add_edge('D', 'T', capacity=6)\n\nflow_val, flow_dict = nx.maximum_flow(G, 'S', 'T')\nprint(f\"最大流: {flow_val}\")\nprint(f\"各边流量: {[(u,v,d) for u,v,d in flow_dict.items() if flow_dict[u]]}\")",
    },
    {
        "category": "图论",
        "name": "PageRank",
        "tags": ["节点重要性", "随机游走", "链接分析"],
        "summary": "通过图的链接结构评估节点重要性的迭代算法。",
        "when": "评估网络节点的相对重要性（影响力、关键节点识别）。",
        "python_libs": "networkx.pagerank",
        "mcm_type": ["D"],
        "difficulty": "简单",
        "code_example": "import networkx as nx\n\n# 有向图: 页面引用关系\nG = nx.DiGraph()\nG.add_edges_from([\n    (0,1), (0,2), (1,2), (1,3), (2,3), (3,0), (3,1), (4,0), (4,2)\n])\n\npr = nx.pagerank(G, alpha=0.85)\nfor node, score in sorted(pr.items(), key=lambda x: -x[1]):\n    print(f\"节点{node}: {score:.4f}\")",
    },
    {
        "category": "图论",
        "name": "社区发现",
        "tags": ["Louvain", "模块度", "图聚类"],
        "summary": "探测网络中的社区结构，识别紧密连接的节点组。",
        "when": "社交网络、生物网络、交通网络的社区划分。",
        "python_libs": "networkx.algorithms.community, python-louvain",
        "mcm_type": ["D"],
        "difficulty": "中等",
        "code_example": "import networkx as nx\nfrom networkx.algorithms.community import greedy_modularity_communities\n\n# Karate Club 网络 (经典社交网络)\nG = nx.karate_club_graph()\n\ncommunities = list(greedy_modularity_communities(G))\nfor i, comm in enumerate(communities):\n    print(f\"社区{i}: {sorted(comm)} (共{len(comm)}人)\")\nprint(f\"模块度: {nx.algorithms.community.modularity(G, communities):.3f}\")",
    },

    # ===== 微分方程 =====
    {
        "category": "方程",
        "name": "常微分方程 (ODE)",
        "tags": ["动力学", "数值求解", "龙格-库塔"],
        "summary": "描述一个变量随另一个变量变化率的关系。",
        "when": "连续动态系统建模（物理过程、种群变化、化学反应）。",
        "python_libs": "scipy.integrate.solve_ivp, scipy.integrate.odeint",
        "mcm_type": ["A", "E"],
        "difficulty": "中等",
        "code_example": "from scipy.integrate import solve_ivp\nimport numpy as np\n\n# Lotka-Volterra 捕食者-猎物模型\ndef lotka_volterra(t, y, a, b, c, d):\n    prey, predator = y\n    return [a*prey - b*prey*predator, -c*predator + d*prey*predator]\n\nsol = solve_ivp(lotka_volterra, [0, 30], [10, 5], args=(1.0, 0.1, 1.5, 0.075), max_step=0.1)\nprint(f\"t=30 时 猎物: {sol.y[0,-1]:.1f}, 捕食者: {sol.y[1,-1]:.1f}\")",
    },
    {
        "category": "方程",
        "name": "偏微分方程 (PDE)",
        "tags": ["有限差分", "有限元", "扩散方程"],
        "summary": "描述多变量函数及其偏导数关系的方程。",
        "when": "热传导、波动传播、流体力学、扩散过程。",
        "python_libs": "numpy (有限差分自行实现), fenics, scipy",
        "mcm_type": ["A"],
        "difficulty": "进阶",
        "code_example": "import numpy as np\n\n# 一维热传导 ∂u/∂t = α ∂²u/∂x², 显式有限差分\nL, T, nx, nt, alpha = 1.0, 0.5, 50, 500, 0.01\ndx, dt = L/(nx-1), T/nt\nr = alpha * dt / dx**2\n\n# 初始条件: 中心高斯温度分布\nu = np.exp(-((np.linspace(0, L, nx) - 0.5)/0.1)**2)\n\nfor _ in range(nt):\n    u[1:-1] += r * (u[:-2] - 2*u[1:-1] + u[2:])\n\nprint(f\"热扩散后中心温度: {u[nx//2]:.4f}, 边界: {u[0]:.4f}\")",
    },
]
